# Generated by Django 3.2.3 on 2021-05-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_smallerprojects'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deepDescription',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smallerprojects',
            name='deepDescription',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
    ]
