# Generated by Django 3.2.3 on 2021-05-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210524_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gitLink',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smallerprojects',
            name='gitLink',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
    ]
